version: '3'
services:
    db:
        image: postgres:10.6
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: digestbot
            POSTGRES_DB: digestbot
            POSTGRES_PASSWORD: digestbot
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
